name: ecommerce
description: "Flutter Test apply to Bemol Job Position"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  dio: ^5.7.0
  intl: ^0.20.1

  flutter_secure_storage: ^9.2.2

  flutter_modular: ^6.3.4
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  cupertino_icons: ^1.0.8

  mockito: ^5.4.5

  shared_preferences: ^2.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  mobx_codegen: ^2.6.1
  analyzer: ^6.2.0
  build_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/home/images/
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
